trigger:
- none

jobs:
- job: windows
  displayName: windows
  pool:
    vmImage: windows-2022
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Hello World"
