trigger:
- master
- features/*
- releases/*

jobs:
#################################################
- job: windows
#################################################
  displayName: windows
  pool:
    vmImage: vs2017-win2016

  steps:
  ################################################################################
  # azure-pipelines-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (azure-pipelines-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 10
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 10.23.0
    inputs:
      versionSpec: "10.23.0"

  # build/test
  - script: |
      chcp 437
      node make.js test
    workingDirectory: node
    displayName: (azure-pipelines-task-lib) node make.js test  

  # build/test
  - script: |
      chcp 437
      node make.js test
    displayName: (azure-pipelines-task-lib) node make.js test
    workingDirectory: node

  ################################################################################
  # VstsTaskSdk
  ################################################################################

  # npm install
  - task: Npm@1
    displayName: (VstsTaskSdk) npm install
    inputs:
      command: install
      workingDir: powershell

  # npm test
  - script: npm test
    displayName: (VstsTaskSdk) npm test
    workingDirectory: powershell

#################################################
- job: linux
#################################################
  displayName: Linux
  pool:
    vmImage: ubuntu-18.04

  steps:
  ################################################################################
  # azure-pipelines-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (azure-pipelines-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 10
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 10.23.0
    inputs:
      versionSpec: "10.23.0"
      
  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (azure-pipelines-task-lib) node make.js test  

  # build/test
  - script: node make.js test
    displayName: (azure-pipelines-task-lib) node make.js test
    workingDirectory: node

  # For CI runs on master, automatically publish packages
  - bash: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        cd _build
        npm publish || true # Ignore publish failures, usually will happen because package already exists
    displayName: (azure-pipelines-task-lib) npm publish
    workingDirectory: node
    condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'Manual'), in(variables['build.sourcebranchname'], 'master', 'releases/3.x'))
    env:
      NPM_TOKEN: $(npmPublishToken)

#################################################
- job: macOS
#################################################
  displayName: macOS
  pool:
    vmImage: macOS-10.15

  steps:
  ################################################################################
  # azure-pipelines-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (azure-pipelines-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 10
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 10.23.0
    inputs:
      versionSpec: "10.23.0"
      
  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (azure-pipelines-task-lib) node make.js test  

  # build/test
  - script: node make.js test
    displayName: (azure-pipelines-task-lib) node make.js test
    workingDirectory: node
